[package]
name = "bkcrack"
version = "0.1.0"
authors = ["Aloxaf <bailong104@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.2"
clap = {version = "^2.32.0", features = ["yaml"]}
chrono = "0.4.6"
